services:
  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: elcom@123
      MYSQL_DATABASE: quan_ly_phong_hoc
      MYSQL_USER: tudao
      MYSQL_PASSWORD: elcom@dtu
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
      - ./db/mysql.cnf:/etc/mysql/conf.d/my.cnf

